[package]
name = "VSS"
version = "1.0.0"
authors = []

[addresses]
ace = "0xcafe"

[dependencies.Group]
local = "../group"

[dependencies.WorkerConfig]
local = "../worker_config"

[dependencies.PKE]
local = "../pke"

[dependencies.FiatShamirTransform]
local = "../fiat-shamir-transform"

[dependencies.SigmaDLogEq]
local = "../sigma-dlog-eq"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
