[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
access_control = "Csx54S8XVLHgY5KW3peJiMaeYUgTirDoTAAGjqcjq1wu"
ace_hook = "CUM2ENS7vKsMLvJ9Njsa1qmvwQwBC6ki1YPvrrcTYv8U"

[programs.testnet]
access_control = "Csx54S8XVLHgY5KW3peJiMaeYUgTirDoTAAGjqcjq1wu"
ace_hook = "CUM2ENS7vKsMLvJ9Njsa1qmvwQwBC6ki1YPvrrcTYv8U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 \"tests/e2e.ts\""
