// Copyright (c) Aptos Labs
// SPDX-License-Identifier: Apache-2.0

//! HTTP server that handles `POST /` requests for threshold-IBE partial key extraction.
//!
//! Request body:  hex-encoded PKE ciphertext (encrypted to this node's registered key) whose
//!                plaintext is a BCS [`verify::WorkerRequest`].
//! Response body: hex-encoded PKE ciphertext (encrypted to the client's key) whose
//!                plaintext is a BCS `tibe.IdentityDecryptionKeyShare` for
//!                decryption flows, or a BCS `ThresholdVrfShare` for tVRF.
//!
//! Adding a new request flow or chain is a one-arm change in `verify::WorkerRequest`
//! and a matching arm here — no manual byte-walking, no per-scheme size tables.
//!
//! ## Per-request structured log line
//!
//! Every request emits **one** JSON-formatted log line (to stderr) tagged with
//! `kind=ACE_REQUEST_HANDLING_SUMMARY`. Fields:
//!
//!   ts                  — UTC timestamp the response was produced
//!   kind                — always `"ACE_REQUEST_HANDLING_SUMMARY"` (search keyword)
//!   handling_session_id — UUID v4, generated by this worker when it begins handling
//!                         the request. Server-side identity; no relationship to any
//!                         client-side identifier.
//!   flow                — `"basic"`, `"custom"`, `"threshold_vrf"`, or `"?"` (when not yet identifiable)
//!   result              — `"ok"` | `"rejected"` | `"error"`
//!   reason              — short label for non-ok outcomes
//!   elapsed_ms          — wall time from request entry to response
//!   detail              — free-text reason detail, optional
//!   share_bytes         — only on `result=ok`
//!   keypair             — first 8 hex chars of keypair_id, once known
//!   epoch               — once the request is parsed
//!   decrypt_ms          — time spent PKE-decrypting the inbound request body
//!   pfn_ms              — time spent in `verify` (sole source of PFN RPC traffic)
//!   extract_ms          — time spent extracting the share + PKE-encrypting the response
//!
//! Together `decrypt_ms + pfn_ms + extract_ms` ≈ `elapsed_ms`; comparing the
//! three components is the cheapest way to attribute per-request latency.
//!
//! ## `GET /secrets` (maintainer mode only)
//!
//! Returns the current snapshot of secret shares + PKE dk + eval-point as JSON
//! (see [`crate::secrets::SecretsSnapshotWire`]). Optionally guarded by a
//! bearer token (config flag `--secrets-auth-token` on the maintainer side and
//! `--s0-auth-token` on the handler side).

use std::sync::Arc;
use std::time::Instant;

use axum::{
    body::Bytes,
    extract::State,
    http::StatusCode,
    routing::{get, post},
    Json, Router,
};
use serde_json::json;
use tokio::sync::Semaphore;
use tower_http::cors::CorsLayer;
use uuid::Uuid;
use vss_common::crypto::pke_encrypt;
use vss_common::normalize_account_addr;
use vss_common::pke::{pke_decrypt_bytes, EncryptionKey};

use crate::secret_usage;
use crate::secrets::{LocalSecrets, SecretsProvider, SecretsSnapshotWire};
use crate::verify::{
    self, BasicFlowRequest, CustomFlowRequest, ThresholdVrfRequest, WorkerRequest,
};
use crate::{now_utc_iso, wlog, ChainRpcConfig};

// ── User-facing handler (POST /) ─────────────────────────────────────────────

/// Shared state for the user-facing request handler. The secrets provider
/// abstracts over monolith/maintainer (in-process) vs handler (remote-cached);
/// `pke_dk_bytes` is loaded directly from CLI on both maintainer and handler,
/// so it never crosses the wire.
#[derive(Clone)]
pub struct AppState {
    pub provider: Arc<SecretsProvider>,
    pub chain_rpc: Arc<ChainRpcConfig>,
    pub concurrency: Arc<Semaphore>,
    pub pke_dk_bytes: Arc<Vec<u8>>,
}

/// Spawn the user-request server. Runs until the process exits.
///
/// CORS is wide open (`Access-Control-Allow-Origin: *`, any method, any header)
/// so browser-based clients (e.g. the Shelby explorer's decrypt flow at
/// `https://explorer.shelby.xyz`, or any dApp using `@aptos-labs/ace-sdk`
/// directly from the page) can read the share response. The endpoint has no
/// cookies, no Authorization, and no per-origin authorization — the response
/// ciphertext is only readable by the holder of the ephemeral PKE key encoded
/// in the request — so there is nothing for the SOP to protect here.
pub async fn run_user_server(port: u16, state: AppState) {
    let app = Router::new()
        .route("/", post(handle_request))
        .route("/healthz", get(handle_healthz))
        .with_state(state)
        .layer(CorsLayer::permissive());
    serve(port, app, "http-server (user)").await;
}

async fn handle_healthz() -> StatusCode {
    StatusCode::OK
}

// ── Secrets-server (GET /secrets, maintainer mode) ───────────────────────────
//
// No app-level auth: maintainer and handler are assumed to live in the same
// private network (Cloud Run `ingress=internal` + IAM run.invoker, or a
// VPC-scoped service).

#[derive(Clone)]
pub struct SecretsServerState {
    pub local: LocalSecrets,
}

pub async fn run_secrets_server(port: u16, state: SecretsServerState) {
    let app = Router::new()
        .route("/secrets", get(handle_get_secrets))
        .route("/healthz", get(handle_secrets_healthz))
        .with_state(state);
    serve(port, app, "http-server (secrets)").await;
}

async fn handle_get_secrets(State(state): State<SecretsServerState>) -> Json<SecretsSnapshotWire> {
    Json(state.local.snapshot_wire().await)
}

async fn handle_secrets_healthz() -> StatusCode {
    StatusCode::OK
}

// ── Common serve helper ──────────────────────────────────────────────────────

async fn serve(port: u16, app: Router, label: &str) {
    let addr = format!("0.0.0.0:{}", port);
    let listener = match tokio::net::TcpListener::bind(&addr).await {
        Ok(l) => l,
        Err(e) => {
            wlog!("{}: bind {} failed: {}", label, addr, e);
            return;
        }
    };
    wlog!("{}: listening on {}", label, addr);
    if let Err(e) = axum::serve(listener, app).await {
        wlog!("{}: serve error: {}", label, e);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    use crate::secrets::{ShareEntry, Snapshot};
    use vss_common::group::SCHEME_BLS12381G2;
    use vss_common::pke::EncryptionKey;
    use vss_common::pke_hpke_x25519_chacha20poly1305 as hpke;

    fn dummy_response_enc_key() -> EncryptionKey {
        EncryptionKey::HpkeX25519ChaCha20Poly1305(hpke::EncryptionKey { pk: vec![0u8; 32] })
    }

    fn snapshot_with_share(keypair_id: &str, epoch: u64, entry: ShareEntry) -> Snapshot {
        let mut entries = HashMap::new();
        entries.insert((keypair_id.to_string(), epoch), entry);
        Snapshot {
            entries: Arc::new(entries),
        }
    }

    #[test]
    fn extract_rejects_vrf_only_share_for_tibe() {
        let keypair_id = "0xkp";
        let epoch = 7;
        let snapshot = snapshot_with_share(
            keypair_id,
            epoch,
            ShareEntry {
                scalar_le32: [1u8; 32],
                group_scheme: SCHEME_BLS12381G2,
                expected_usage: secret_usage::USAGE_BLS12381_THRESHOLD_VRF,
                eval_point: 2,
                note: "vrf only".to_string(),
            },
        );

        let outcome = extract_and_respond(
            &snapshot,
            keypair_id,
            epoch,
            b"identity",
            &dummy_response_enc_key(),
            crate::crypto::SCHEME_BFIBE_BLS12381_SHORTSIG_AEAD,
        );

        match outcome {
            Outcome::Rejected {
                reason: Reason::BadRequest,
                detail,
            } => {
                assert!(detail
                    .unwrap_or_default()
                    .contains("does not allow tibe_scheme"));
            }
            _ => panic!("expected BadRequest rejection for VRF-only share"),
        }
    }
}

// ── User-request handler internals ───────────────────────────────────────────

fn new_handling_session_id() -> String {
    Uuid::new_v4().to_string()
}

#[derive(Copy, Clone)]
enum Flow {
    Unknown,
    Basic,
    Custom,
    ThresholdVrf,
}

impl Flow {
    fn label(self) -> &'static str {
        match self {
            Flow::Unknown => "?",
            Flow::Basic => "basic",
            Flow::Custom => "custom",
            Flow::ThresholdVrf => "threshold_vrf",
        }
    }
}

#[derive(Copy, Clone)]
enum Reason {
    BadRequest,
    Forbidden,
    NotFound,
    ServiceUnavailable,
    TooManyRequests,
    Internal,
}

impl Reason {
    fn label(self) -> &'static str {
        match self {
            Reason::BadRequest => "bad_request",
            Reason::Forbidden => "forbidden",
            Reason::NotFound => "not_found",
            Reason::ServiceUnavailable => "service_unavailable",
            Reason::TooManyRequests => "too_many_requests",
            Reason::Internal => "internal",
        }
    }
    fn status(self) -> StatusCode {
        match self {
            Reason::BadRequest => StatusCode::BAD_REQUEST,
            Reason::Forbidden => StatusCode::FORBIDDEN,
            Reason::NotFound => StatusCode::NOT_FOUND,
            Reason::ServiceUnavailable => StatusCode::SERVICE_UNAVAILABLE,
            Reason::TooManyRequests => StatusCode::TOO_MANY_REQUESTS,
            Reason::Internal => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }
    fn result_label(self) -> &'static str {
        match self {
            Reason::Internal => "error",
            _ => "rejected",
        }
    }
}

enum Outcome {
    Ok {
        share_hex: String,
    },
    Rejected {
        reason: Reason,
        detail: Option<String>,
    },
}

#[derive(Default)]
struct RequestContext {
    flow: Option<Flow>,
    keypair_short: Option<String>,
    epoch: Option<u64>,
    enc_pk_hex: Option<String>,
    decrypt_ms: Option<u64>,
    pfn_ms: Option<u64>,
    extract_ms: Option<u64>,
}

async fn handle_request(State(state): State<AppState>, body: Bytes) -> Result<String, StatusCode> {
    let handling_session_id = new_handling_session_id();
    let start = Instant::now();
    let mut ctx = RequestContext::default();

    let outcome = handle_request_inner(&state, &body, &mut ctx).await;
    let elapsed_ms = start.elapsed().as_millis() as u64;
    let flow = ctx.flow.unwrap_or(Flow::Unknown).label();

    let mut log = json!({
        "ts": now_utc_iso(),
        "kind": "ACE_REQUEST_HANDLING_SUMMARY",
        "handling_session_id": handling_session_id,
        "flow": flow,
        "elapsed_ms": elapsed_ms,
    });
    if let Some(kp) = ctx.keypair_short.as_deref() {
        log["keypair"] = json!(kp);
    }
    if let Some(e) = ctx.epoch {
        log["epoch"] = json!(e);
    }
    if let Some(pk) = ctx.enc_pk_hex.as_deref() {
        log["enc_pk"] = json!(pk);
    }
    if let Some(v) = ctx.decrypt_ms {
        log["decrypt_ms"] = json!(v);
    }
    if let Some(v) = ctx.pfn_ms {
        log["pfn_ms"] = json!(v);
    }
    if let Some(v) = ctx.extract_ms {
        log["extract_ms"] = json!(v);
    }

    match outcome {
        Outcome::Ok { share_hex } => {
            log["result"] = json!("ok");
            log["share_bytes"] = json!(share_hex.len() / 2);
            eprintln!("{}", log);
            Ok(share_hex)
        }
        Outcome::Rejected { reason, detail } => {
            log["result"] = json!(reason.result_label());
            log["reason"] = json!(reason.label());
            if let Some(d) = detail {
                log["detail"] = json!(d);
            }
            eprintln!("{}", log);
            Err(reason.status())
        }
    }
}

async fn handle_request_inner(state: &AppState, body: &[u8], ctx: &mut RequestContext) -> Outcome {
    let _permit = match Arc::clone(&state.concurrency).try_acquire_owned() {
        Ok(p) => p,
        Err(_) => {
            return Outcome::Rejected {
                reason: Reason::TooManyRequests,
                detail: None,
            };
        }
    };

    let body_str = match std::str::from_utf8(body) {
        Ok(s) => s,
        Err(_) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some("body is not valid utf-8".to_string()),
            };
        }
    };
    let ct_bytes = match hex::decode(body_str.trim()) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("hex decode failed: {}", e)),
            };
        }
    };

    let decrypt_start = Instant::now();
    let req_bytes = match pke_decrypt_bytes(state.pke_dk_bytes.as_ref(), &ct_bytes) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("pke decrypt failed: {:#}", e)),
            };
        }
    };
    ctx.decrypt_ms = Some(decrypt_start.elapsed().as_millis() as u64);

    let request: WorkerRequest = match bcs::from_bytes(&req_bytes) {
        Ok(r) => r,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("bcs decode WorkerRequest failed: {}", e)),
            };
        }
    };

    // Fetch the secrets snapshot. In monolith/maintainer this is a cheap clone of
    // in-process state; in handler mode this is the singleflight remote cache.
    let snapshot = match state.provider.snapshot().await {
        Ok(s) => s,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::ServiceUnavailable,
                detail: Some(format!("secrets fetch failed: {:#}", e)),
            };
        }
    };

    match request {
        WorkerRequest::DecryptionBasicFlow(req) => {
            ctx.flow = Some(Flow::Basic);
            ctx.keypair_short = Some(short_hex(&req.payload.keypair_id));
            ctx.epoch = Some(req.payload.epoch);
            ctx.enc_pk_hex = enc_pk_to_hex(&req.payload.ephemeral_enc_key);
            let v1 = BasicFlowRequest {
                payload: req.payload,
                proof: req.proof,
            };
            handle_basic_flow(state, &snapshot, v1, req.tibe_scheme, ctx).await
        }
        WorkerRequest::DecryptionCustomFlow(req) => {
            ctx.flow = Some(Flow::Custom);
            ctx.keypair_short = Some(short_hex(&req.keypair_id));
            ctx.epoch = Some(req.epoch);
            ctx.enc_pk_hex = enc_pk_to_hex(&req.enc_pk);
            let v1 = CustomFlowRequest {
                keypair_id: req.keypair_id,
                epoch: req.epoch,
                contract_id: req.contract_id,
                label: req.label,
                enc_pk: req.enc_pk,
                proof: req.proof,
            };
            handle_custom_flow(state, &snapshot, v1, req.tibe_scheme, ctx).await
        }
        WorkerRequest::ThresholdVrf(req) => {
            ctx.flow = Some(Flow::ThresholdVrf);
            ctx.keypair_short = Some(short_hex(&req.payload.keypair_id));
            ctx.epoch = Some(req.payload.epoch);
            ctx.enc_pk_hex = enc_pk_to_hex(&req.payload.response_enc_key);
            handle_threshold_vrf(state, &snapshot, req, ctx).await
        }
    }
}

fn enc_pk_to_hex(ek: &EncryptionKey) -> Option<String> {
    bcs::to_bytes(ek).ok().map(hex::encode)
}

async fn handle_basic_flow(
    state: &AppState,
    snapshot: &crate::secrets::Snapshot,
    req: BasicFlowRequest,
    tibe_scheme: u8,
    ctx: &mut RequestContext,
) -> Outcome {
    let pfn_start = Instant::now();
    let verify_result = verify::verify_basic(&req, &state.chain_rpc).await;
    ctx.pfn_ms = Some(pfn_start.elapsed().as_millis() as u64);
    if let Err(e) = verify_result {
        return Outcome::Rejected {
            reason: Reason::Forbidden,
            detail: Some(format!("{:#}", e)),
        };
    }
    let identity = verify::identity_bytes(
        &req.payload.keypair_id,
        &req.payload.contract_id,
        &req.payload.domain,
    );
    let keypair_id = keypair_id_str(&req.payload.keypair_id);
    let extract_start = Instant::now();
    let outcome = extract_and_respond(
        snapshot,
        &keypair_id,
        req.payload.epoch,
        &identity,
        &req.payload.ephemeral_enc_key,
        tibe_scheme,
    );
    ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
    outcome
}

async fn handle_custom_flow(
    state: &AppState,
    snapshot: &crate::secrets::Snapshot,
    req: CustomFlowRequest,
    tibe_scheme: u8,
    ctx: &mut RequestContext,
) -> Outcome {
    let pfn_start = Instant::now();
    let verify_result = verify::verify_custom(&req, &state.chain_rpc).await;
    ctx.pfn_ms = Some(pfn_start.elapsed().as_millis() as u64);
    if let Err(e) = verify_result {
        return Outcome::Rejected {
            reason: Reason::Forbidden,
            detail: Some(format!("{:#}", e)),
        };
    }
    // Custom-flow identity uses `label` in place of `domain`; ContractId is unchanged.
    let identity = verify::identity_bytes(&req.keypair_id, &req.contract_id, &req.label);
    let keypair_id = keypair_id_str(&req.keypair_id);
    let extract_start = Instant::now();
    let outcome = extract_and_respond(
        snapshot,
        &keypair_id,
        req.epoch,
        &identity,
        &req.enc_pk,
        tibe_scheme,
    );
    ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
    outcome
}

async fn handle_threshold_vrf(
    state: &AppState,
    snapshot: &crate::secrets::Snapshot,
    req: ThresholdVrfRequest,
    ctx: &mut RequestContext,
) -> Outcome {
    let pfn_start = Instant::now();
    let verify_result = verify::verify_threshold_vrf(&req, &state.chain_rpc).await;
    ctx.pfn_ms = Some(pfn_start.elapsed().as_millis() as u64);
    if let Err(e) = verify_result {
        return Outcome::Rejected {
            reason: Reason::Forbidden,
            detail: Some(format!("{:#}", e)),
        };
    }

    let keypair_id = keypair_id_str(&req.payload.keypair_id);
    let extract_start = Instant::now();
    let entry = match snapshot.lookup(&keypair_id, req.payload.epoch) {
        Some(v) => v,
        None => {
            ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
            return Outcome::Rejected {
                reason: Reason::NotFound,
                detail: Some(format!(
                    "no share for keypair_id={} epoch={}",
                    keypair_id, req.payload.epoch
                )),
            };
        }
    };
    if !secret_usage::allows_usage(
        entry.expected_usage,
        secret_usage::USAGE_BLS12381_THRESHOLD_VRF,
    ) {
        ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
        return Outcome::Rejected {
            reason: Reason::BadRequest,
            detail: Some(format!(
                "keypair_id={} epoch={} usage mask {} does not allow threshold VRF",
                keypair_id, req.payload.epoch, entry.expected_usage
            )),
        };
    }

    let share_bytes = match crate::crypto::partial_derive_threshold_vrf_share(
        &req.payload.keypair_id,
        &req.payload.contract_id,
        &req.payload.account_address,
        &req.payload.label,
        &entry.scalar_le32,
        entry.eval_point,
        entry.group_scheme,
    ) {
        Ok(s) => s,
        Err(e) => {
            ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
            return Outcome::Rejected {
                reason: Reason::Internal,
                detail: Some(format!("partial_derive_threshold_vrf_share: {:#}", e)),
            };
        }
    };
    let resp_ct = pke_encrypt(&req.payload.response_enc_key, &share_bytes);
    let outcome = match bcs::to_bytes(&resp_ct) {
        Ok(b) => Outcome::Ok {
            share_hex: hex::encode(b),
        },
        Err(e) => Outcome::Rejected {
            reason: Reason::Internal,
            detail: Some(format!("bcs encode response: {}", e)),
        },
    };
    ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
    outcome
}

fn keypair_id_str(keypair_id: &[u8; 32]) -> String {
    normalize_account_addr(&format!("0x{}", hex::encode(keypair_id)))
}

fn short_hex(keypair_id: &[u8; 32]) -> String {
    hex::encode(&keypair_id[..4])
}

fn extract_and_respond(
    snapshot: &crate::secrets::Snapshot,
    keypair_id: &str,
    epoch: u64,
    identity: &[u8],
    response_enc_key: &EncryptionKey,
    tibe_scheme: u8,
) -> Outcome {
    // Empty entries (no shares yet, or this node isn't in the committee) and a
    // simple keypair/epoch miss both map to NotFound; the operator-facing
    // distinction lives in the maintainer's logs, not in the response.
    let entry = match snapshot.lookup(keypair_id, epoch) {
        Some(v) => v,
        None => {
            return Outcome::Rejected {
                reason: Reason::NotFound,
                detail: Some(format!(
                    "no share for keypair_id={} epoch={}",
                    keypair_id, epoch
                )),
            };
        }
    };

    match crate::crypto::group_scheme_for_tibe(tibe_scheme) {
        Ok(expected_group) if expected_group == entry.group_scheme => {}
        Ok(expected_group) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!(
                    "tibe_scheme {} requires group {}, but share's group is {}",
                    tibe_scheme, expected_group, entry.group_scheme
                )),
            };
        }
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("unknown tibe_scheme {}: {:#}", tibe_scheme, e)),
            };
        }
    }

    let required_usage = match secret_usage::usage_for_tibe_scheme(tibe_scheme) {
        Ok(u) => u,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("unknown tibe_scheme {}: {:#}", tibe_scheme, e)),
            };
        }
    };
    if !secret_usage::allows_usage(entry.expected_usage, required_usage) {
        return Outcome::Rejected {
            reason: Reason::BadRequest,
            detail: Some(format!(
                "keypair_id={} epoch={} usage mask {} does not allow tibe_scheme {}",
                keypair_id, epoch, entry.expected_usage, tibe_scheme
            )),
        };
    }

    let share_hex = match crate::crypto::partial_extract_idk_share(
        tibe_scheme,
        identity,
        &entry.scalar_le32,
        entry.eval_point,
    ) {
        Ok(s) => s,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::Internal,
                detail: Some(format!("partial_extract_idk_share: {:#}", e)),
            };
        }
    };
    let share_bytes = match hex::decode(&share_hex) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::Internal,
                detail: Some(format!("hex decode of share: {}", e)),
            };
        }
    };
    let resp_ct = pke_encrypt(response_enc_key, &share_bytes);
    match bcs::to_bytes(&resp_ct) {
        Ok(b) => Outcome::Ok {
            share_hex: hex::encode(b),
        },
        Err(e) => Outcome::Rejected {
            reason: Reason::Internal,
            detail: Some(format!("bcs encode response: {}", e)),
        },
    }
}
