// Copyright (c) Aptos Labs
// SPDX-License-Identifier: Apache-2.0

//! HTTP server that handles `POST /` requests for threshold-IBE partial key extraction.
//!
//! Request body:  hex-encoded PKE ciphertext (encrypted to this node's registered key) whose
//!                plaintext is a BCS [`verify::RequestForDecryptionKey`].
//! Response body: hex-encoded PKE ciphertext (encrypted to the client's key) whose
//!                plaintext is a BCS `tibe.IdentityDecryptionKeyShare`.
//!
//! Adding a new request flow or chain is a one-arm change in `verify::RequestForDecryptionKey`
//! and a matching arm here — no manual byte-walking, no per-scheme size tables.
//!
//! ## Per-request structured log line
//!
//! Every request emits **one** JSON-formatted log line (to stderr) tagged with
//! `kind=ACE_REQUEST_HANDLING_SUMMARY`. Fields:
//!
//!   ts                  — UTC ISO timestamp the response was produced
//!   kind                — always `"ACE_REQUEST_HANDLING_SUMMARY"` (search keyword)
//!   handling_session_id — UUID v4, generated by this worker when it begins handling
//!                         the request. Server-side identity; no relationship to any
//!                         client-side identifier.
//!   flow                — `"basic"`, `"custom"`, or `"?"` (when not yet identifiable)
//!   result      — `"ok"` | `"rejected"` | `"error"`
//!   reason      — short label for non-ok outcomes (see `Reason` enum below)
//!   elapsed_ms  — wall time from request entry to response
//!   detail      — free-text reason detail (e.g. underlying error message), optional
//!   share_bytes — only on `result=ok`
//!   keypair     — first 8 hex chars of keypair_id, populated once known
//!   epoch       — populated once the request is parsed
//!   decrypt_ms  — time spent PKE-decrypting the inbound request body
//!   pfn_ms      — time spent in `verify` (sole source of PFN RPC traffic)
//!   extract_ms  — time spent extracting the share + PKE-encrypting the response
//!
//! Together `decrypt_ms + pfn_ms + extract_ms` ≈ `elapsed_ms`; comparing the
//! three components is the cheapest way to attribute per-request latency
//! during load tests.
//!
//! The keyword `ACE_REQUEST_HANDLING_SUMMARY` is intentionally distinctive so it doesn't
//! collide with anything else in the log stream. Humio (and similar log aggregators)
//! auto-extract JSON fields when the entire line is a single JSON object.

use std::collections::HashMap;
use std::sync::Arc;
use std::time::Instant;

use axum::{body::Bytes, extract::State, http::StatusCode, routing::post, Router};
use serde_json::json;
use tokio::sync::{RwLock, Semaphore};
use uuid::Uuid;
use vss_common::crypto::pke_encrypt;
use vss_common::normalize_account_addr;
use vss_common::pke::{pke_decrypt_bytes, EncryptionKey};

use crate::verify::{self, BasicFlowRequest, CustomFlowRequest, RequestForDecryptionKey};
use crate::{now_utc_iso, wlog, ChainRpcConfig};

/// Shared state for the HTTP handler.
#[derive(Clone)]
pub struct AppState {
    pub keypair_shares: Arc<RwLock<HashMap<String, HashMap<u64, ([u8; 32], u8)>>>>,
    pub cur_nodes: Arc<RwLock<Vec<String>>>,
    pub my_addr: String,
    /// Per-chain RPC config, used for on-chain proof verification.
    pub chain_rpc: Arc<ChainRpcConfig>,
    /// This node's PKE decryption key bytes, used to decrypt incoming requests.
    pub pke_dk_bytes: Vec<u8>,
    /// Bounds the number of simultaneously in-flight requests.
    pub concurrency: Arc<Semaphore>,
}

/// Spawn the axum server on `port`.  Runs until the process exits.
pub async fn run(
    port: u16,
    keypair_shares: Arc<RwLock<HashMap<String, HashMap<u64, ([u8; 32], u8)>>>>,
    cur_nodes: Arc<RwLock<Vec<String>>>,
    my_addr: String,
    chain_rpc: Arc<ChainRpcConfig>,
    pke_dk_bytes: Vec<u8>,
    concurrency: Arc<Semaphore>,
) {
    let state = AppState { keypair_shares, cur_nodes, my_addr, chain_rpc, pke_dk_bytes, concurrency };
    let app = Router::new().route("/", post(handle_request)).with_state(state);
    let addr = format!("0.0.0.0:{}", port);
    let listener = match tokio::net::TcpListener::bind(&addr).await {
        Ok(l) => l,
        Err(e) => {
            wlog!("http-server: bind {} failed: {}", addr, e);
            return;
        }
    };
    wlog!("http-server: listening on {}", addr);
    if let Err(e) = axum::serve(listener, app).await {
        wlog!("http-server: serve error: {}", e);
    }
}

/// Server-side handling-session id. Unique across process restarts and across
/// Cloud Run replicas. UUID v4 is overkill for in-process correlation but the
/// right tool when the log stream is merged from many instances downstream
/// (Cloud Logging / Humio).
fn new_handling_session_id() -> String {
    Uuid::new_v4().to_string()
}

#[derive(Copy, Clone)]
enum Flow {
    Unknown,
    Basic,
    Custom,
}

impl Flow {
    fn label(self) -> &'static str {
        match self {
            Flow::Unknown => "?",
            Flow::Basic => "basic",
            Flow::Custom => "custom",
        }
    }
}

/// Short label for the `reason` field on non-`ok` outcomes.
#[derive(Copy, Clone)]
enum Reason {
    BadRequest,
    Forbidden,
    NotFound,
    ServiceUnavailable,
    TooManyRequests,
    Internal,
}

impl Reason {
    fn label(self) -> &'static str {
        match self {
            Reason::BadRequest => "bad_request",
            Reason::Forbidden => "forbidden",
            Reason::NotFound => "not_found",
            Reason::ServiceUnavailable => "service_unavailable",
            Reason::TooManyRequests => "too_many_requests",
            Reason::Internal => "internal",
        }
    }
    fn status(self) -> StatusCode {
        match self {
            Reason::BadRequest => StatusCode::BAD_REQUEST,
            Reason::Forbidden => StatusCode::FORBIDDEN,
            Reason::NotFound => StatusCode::NOT_FOUND,
            Reason::ServiceUnavailable => StatusCode::SERVICE_UNAVAILABLE,
            Reason::TooManyRequests => StatusCode::TOO_MANY_REQUESTS,
            Reason::Internal => StatusCode::INTERNAL_SERVER_ERROR,
        }
    }
    /// Most reasons are client-caused rejections; `Internal` is the only one
    /// we classify as a server-side error in the log.
    fn result_label(self) -> &'static str {
        match self {
            Reason::Internal => "error",
            _ => "rejected",
        }
    }
}

/// What an inner handler produces. The outer wrapper turns this into a single
/// log line + the appropriate HTTP response.
enum Outcome {
    Ok {
        share_hex: String,
    },
    Rejected {
        reason: Reason,
        detail: Option<String>,
    },
}

/// Accumulator passed down through the inner handlers so they can populate
/// fields as soon as they become known. The outer wrapper reads these when
/// emitting the log line.
#[derive(Default)]
struct RequestContext {
    flow: Option<Flow>,
    keypair_short: Option<String>,
    epoch: Option<u64>,
    /// BCS-then-hex encoding of the response encryption key from the request
    /// (basic flow: `ephemeral_enc_key`; custom flow: `enc_pk`). Lets the
    /// driver correlate worker log lines with the exact requests it sent.
    enc_pk_hex: Option<String>,
    /// PKE-decrypt of the inbound request body.
    decrypt_ms: Option<u64>,
    /// `verify_basic` / `verify_custom`, which is the only place we hit the PFN.
    pfn_ms: Option<u64>,
    /// Share extraction + PKE-encrypt of the response.
    extract_ms: Option<u64>,
}

async fn handle_request(
    State(state): State<AppState>,
    body: Bytes,
) -> Result<String, StatusCode> {
    let handling_session_id = new_handling_session_id();
    let start = Instant::now();
    let mut ctx = RequestContext::default();

    let outcome = handle_request_inner(&state, &body, &mut ctx).await;
    let elapsed_ms = start.elapsed().as_millis() as u64;
    let flow = ctx.flow.unwrap_or(Flow::Unknown).label();

    let mut log = json!({
        "ts": now_utc_iso(),
        "kind": "ACE_REQUEST_HANDLING_SUMMARY",
        "handling_session_id": handling_session_id,
        "flow": flow,
        "elapsed_ms": elapsed_ms,
    });
    if let Some(kp) = ctx.keypair_short.as_deref() {
        log["keypair"] = json!(kp);
    }
    if let Some(e) = ctx.epoch {
        log["epoch"] = json!(e);
    }
    if let Some(pk) = ctx.enc_pk_hex.as_deref() {
        log["enc_pk"] = json!(pk);
    }
    if let Some(v) = ctx.decrypt_ms {
        log["decrypt_ms"] = json!(v);
    }
    if let Some(v) = ctx.pfn_ms {
        log["pfn_ms"] = json!(v);
    }
    if let Some(v) = ctx.extract_ms {
        log["extract_ms"] = json!(v);
    }

    match outcome {
        Outcome::Ok { share_hex } => {
            log["result"] = json!("ok");
            log["share_bytes"] = json!(share_hex.len() / 2);
            eprintln!("{}", log);
            Ok(share_hex)
        }
        Outcome::Rejected { reason, detail } => {
            log["result"] = json!(reason.result_label());
            log["reason"] = json!(reason.label());
            if let Some(d) = detail {
                log["detail"] = json!(d);
            }
            eprintln!("{}", log);
            Err(reason.status())
        }
    }
}

async fn handle_request_inner(state: &AppState, body: &[u8], ctx: &mut RequestContext) -> Outcome {
    let _permit = match Arc::clone(&state.concurrency).try_acquire_owned() {
        Ok(p) => p,
        Err(_) => {
            return Outcome::Rejected { reason: Reason::TooManyRequests, detail: None };
        }
    };

    let body_str = match std::str::from_utf8(body) {
        Ok(s) => s,
        Err(_) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some("body is not valid utf-8".to_string()),
            };
        }
    };
    let ct_bytes = match hex::decode(body_str.trim()) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("hex decode failed: {}", e)),
            };
        }
    };

    let decrypt_start = Instant::now();
    let req_bytes = match pke_decrypt_bytes(&state.pke_dk_bytes, &ct_bytes) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("pke decrypt failed: {:#}", e)),
            };
        }
    };
    ctx.decrypt_ms = Some(decrypt_start.elapsed().as_millis() as u64);

    let request: RequestForDecryptionKey = match bcs::from_bytes(&req_bytes) {
        Ok(r) => r,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::BadRequest,
                detail: Some(format!("bcs decode RequestForDecryptionKey failed: {}", e)),
            };
        }
    };

    match request {
        RequestForDecryptionKey::Basic(req) => {
            ctx.flow = Some(Flow::Basic);
            ctx.keypair_short = Some(short_hex(&req.keypair_id));
            ctx.epoch = Some(req.epoch);
            ctx.enc_pk_hex = enc_pk_to_hex(&req.ephemeral_enc_key);
            handle_basic_flow(state, req, ctx).await
        }
        RequestForDecryptionKey::Custom(req) => {
            ctx.flow = Some(Flow::Custom);
            ctx.keypair_short = Some(short_hex(&req.keypair_id));
            ctx.epoch = Some(req.epoch);
            ctx.enc_pk_hex = enc_pk_to_hex(&req.enc_pk);
            handle_custom_flow(state, req, ctx).await
        }
    }
}

/// BCS-then-hex encode the EncryptionKey. None on serialization failure (we'd
/// rather drop the field than fail the whole request just to populate a log).
fn enc_pk_to_hex(ek: &EncryptionKey) -> Option<String> {
    bcs::to_bytes(ek).ok().map(hex::encode)
}

async fn handle_basic_flow(
    state: &AppState,
    req: BasicFlowRequest,
    ctx: &mut RequestContext,
) -> Outcome {
    let pfn_start = Instant::now();
    let verify_result = verify::verify_basic(&req, &state.chain_rpc).await;
    ctx.pfn_ms = Some(pfn_start.elapsed().as_millis() as u64);
    if let Err(e) = verify_result {
        return Outcome::Rejected {
            reason: Reason::Forbidden,
            detail: Some(format!("{:#}", e)),
        };
    }
    let identity = verify::identity_bytes(&req.keypair_id, &req.contract_id, &req.domain);
    let keypair_id = keypair_id_str(&req.keypair_id);
    let extract_start = Instant::now();
    let outcome =
        extract_and_respond(state, &keypair_id, req.epoch, &identity, &req.ephemeral_enc_key).await;
    ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
    outcome
}

async fn handle_custom_flow(
    state: &AppState,
    req: CustomFlowRequest,
    ctx: &mut RequestContext,
) -> Outcome {
    let pfn_start = Instant::now();
    let verify_result = verify::verify_custom(&req, &state.chain_rpc).await;
    ctx.pfn_ms = Some(pfn_start.elapsed().as_millis() as u64);
    if let Err(e) = verify_result {
        return Outcome::Rejected {
            reason: Reason::Forbidden,
            detail: Some(format!("{:#}", e)),
        };
    }
    // Custom-flow identity uses `label` in place of `domain`; ContractId is unchanged.
    let identity = verify::identity_bytes(&req.keypair_id, &req.contract_id, &req.label);
    let keypair_id = keypair_id_str(&req.keypair_id);
    let extract_start = Instant::now();
    let outcome =
        extract_and_respond(state, &keypair_id, req.epoch, &identity, &req.enc_pk).await;
    ctx.extract_ms = Some(extract_start.elapsed().as_millis() as u64);
    outcome
}

fn keypair_id_str(keypair_id: &[u8; 32]) -> String {
    normalize_account_addr(&format!("0x{}", hex::encode(keypair_id)))
}

fn short_hex(keypair_id: &[u8; 32]) -> String {
    hex::encode(&keypair_id[..4])
}

/// Look up the scalar share, compute the IDK share, and encrypt it to `response_enc_key`.
async fn extract_and_respond(
    state: &AppState,
    keypair_id: &str,
    epoch: u64,
    identity: &[u8],
    response_enc_key: &EncryptionKey,
) -> Outcome {
    let lookup = {
        let shares = state.keypair_shares.read().await;
        shares
            .get(keypair_id)
            .and_then(|by_epoch| by_epoch.get(&epoch))
            .copied()
    };
    let (scalar_le32, tibe_scheme) = match lookup {
        Some(v) => v,
        None => {
            return Outcome::Rejected {
                reason: Reason::NotFound,
                detail: Some(format!(
                    "no share for keypair_id={} epoch={}",
                    keypair_id, epoch
                )),
            };
        }
    };

    let eval_point = {
        let nodes = state.cur_nodes.read().await;
        nodes
            .iter()
            .position(|n| n == &state.my_addr)
            .map(|i| (i + 1) as u64)
    };
    let eval_point = match eval_point {
        Some(e) => e,
        None => {
            return Outcome::Rejected {
                reason: Reason::ServiceUnavailable,
                detail: Some("this node is not in cur_nodes".to_string()),
            };
        }
    };

    let share_hex = match crate::crypto::partial_extract_idk_share(
        tibe_scheme,
        identity,
        &scalar_le32,
        eval_point,
    ) {
        Ok(s) => s,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::Internal,
                detail: Some(format!("partial_extract_idk_share: {:#}", e)),
            };
        }
    };
    let share_bytes = match hex::decode(&share_hex) {
        Ok(b) => b,
        Err(e) => {
            return Outcome::Rejected {
                reason: Reason::Internal,
                detail: Some(format!("hex decode of share: {}", e)),
            };
        }
    };
    let resp_ct = pke_encrypt(response_enc_key, &share_bytes);
    match bcs::to_bytes(&resp_ct) {
        Ok(b) => Outcome::Ok { share_hex: hex::encode(b) },
        Err(e) => Outcome::Rejected {
            reason: Reason::Internal,
            detail: Some(format!("bcs encode response: {}", e)),
        },
    }
}
