[package]
name = "WorkerConfig"
version = "1.0.0"
authors = []

[addresses]
ace = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.PKE]
local = "../pke"
