// Copyright (c) Aptos Labs
// SPDX-License-Identifier: Apache-2.0

/**
 * Script 3 — Issue KYC Credential
 *
 * The KYC provider issues a credential binding a user's secret to their age.
 * Concretely, the provider signs Poseidon(user_secret, age) — analogous to
 * attesting "this user's age is X" without naming the user.
 *
 * user_secret is generated by the user (step 3a below) and shared with the
 * provider out-of-band during the KYC verification session.  It never appears
 * on-chain or in any proof — only its hash is committed to.
 *
 * Usage:
 *   pnpm 3-issue-credential            # defaults to age 25
 *   pnpm 3-issue-credential -- 30      # age 30
 *
 * Ages below 18 are accepted here — the ZK proof will fail at step 5 since
 * the circuit enforces the age >= 18 constraint.
 *
 * Output: data/credential.json  (user_secret + age + provider signature)
 */

import { buildEddsa, buildPoseidon } from 'circomlibjs';
import * as path from 'path';
import { DATA_DIR, ensureDataDir, readJson, writeJson } from './common.js';

interface ProviderKey {
    private: string;
    public_ax: string;
    public_ay: string;
}

async function main() {
    ensureDataDir();

    const rawArg = process.argv.slice(2).find(a => a !== '--');
    const age = parseInt(rawArg ?? '25', 10);
    if (isNaN(age) || age < 0 || age > 255) {
        console.error('age must be an integer 0–255');
        process.exit(1);
    }

    const status = age >= 18 ? 'eligible (18+)' : 'underage (<18)';
    console.log(`Issuing credential for age ${age} — ${status}`);

    const providerKeyPath = path.join(DATA_DIR, 'provider-key.json');
    const providerKey = readJson<ProviderKey>(providerKeyPath);

    const poseidon = await buildPoseidon();
    const eddsa = await buildEddsa();
    const F = eddsa.F;

    // The user generates a random secret that only they know.
    // In production this would be derived from a wallet seed or stored securely.
    const userSecretBytes = new Uint8Array(31); // 31 bytes → safely < BN254 Fr order
    crypto.getRandomValues(userSecretBytes);
    const userSecret = BigInt('0x' + Buffer.from(userSecretBytes).toString('hex'));

    const privKey = Buffer.from(providerKey.private, 'hex');

    // Provider signs Poseidon(user_secret, age) — binding both identity and age.
    const msgHash = poseidon([userSecret, BigInt(age)]);
    const sig = eddsa.signPoseidon(privKey, msgHash);

    const credential = {
        user_secret: userSecret.toString(),
        age,
        sig_r8x: F.toObject(sig.R8[0]).toString(),
        sig_r8y: F.toObject(sig.R8[1]).toString(),
        sig_s:   sig.S.toString(),
    };

    const outPath = path.join(DATA_DIR, 'credential.json');
    writeJson(outPath, credential);

    console.log(`Credential issued and saved to ${outPath}`);
    console.log(`  Age: ${age} (${status})`);
    console.log('');
    console.log('Next: run script 4 to encrypt a secret under this KYC policy.');
}

main().catch(err => { console.error(err); process.exit(1); });
