[package]
name = "ShelbyPresignedAccess"
version = "0.1.0"
authors = []

[addresses]
admin = "_"

[dev-addresses]
admin = "0xcafe"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
